Update xsibackup

diff --git a/xsibackup b/xsibackup
--- a/xsibackup
+++ b/xsibackup
@@ -70,7 +70,7 @@ newdirmask=$(date +%Y%m%d''%H%M%S)
 # yearstring=$(date +%Y)
 yearstring="20"
 
-help=$'© 33HOPS, Sistemas de Informacion y Redes, S.L. - 33hops.com - © xsibackup 4.2.5\r
+help=$'© 33HOPS, Sistemas de Informacion y Redes, S.L. - 33hops.com - © xsibackup 4.3.0\r
 Backup Utility for the © VMware ESXi 5.X Hypervisor Series
 
 RULES:
@@ -125,7 +125,10 @@ OPTIONS:
 			You can use any string, full or partial, that may help identify the disk by its name
 			or by its device descriptor. Take on account that if you use an ambiguous string per
 			instance "scsi" more than one disk may be excluded. This parameter is only needed if 
-			custom is selected as the --backup-type
+			custom is selected as the --backup-type.
+
+--backup-prog		Defaults to Rsync for TCP/IP backups and to vmkfstools for datastore backups, unless
+			explicitly set to rsync. In this case local copies will be done by means of rsync.
 
 --test-mode=true	Allows testing backup procedure and e-mail submission without having to wait for a
 			full backup process. In this mode VMs are not copied to the backup disk.
@@ -148,6 +151,8 @@ OPTIONS:
 			the only authentication method supported by xsibackup\'s email client by now.
 
 --smtp-pwd		SMTP password used for authentication against the SMTP server.			
+
+--smtp-sec		SMTP authentication scheme, set it =TLS (upper case) if needed, default is no encription
 
 --link-srv		This command needs an argument like this --link-srv=192.168.0.100. It generates a DSA
 			key locally and adds it to the authorized_keys file at the remote host allowing to
@@ -536,6 +541,12 @@ if [[ -z ${smtpsrv} ]]
 then
         SEND_EMAIL=0
         SEND_EMAIL_MSG=$SEND_EMAIL_MSG"The --smtp-srv string has not been set.$newline"
+fi
+
+if [[ -z ${smtpport} ]]
+then
+        SEND_EMAIL=0
+        SEND_EMAIL_MSG=$SEND_EMAIL_MSG"The --smtp-port string has not been set.$newline"
 fi
 
 if [[ -z ${smtpauth} ]]
@@ -1014,7 +1025,6 @@ cloneVM(){
 
 	if [ "$SERVERTYPE" = "DIR" ]
 	then
-$( echo \"$2\" >> prueba.txt )	
 		if [ -d "$2" ]
         	then
                 	rm -rf "$2/"*
@@ -1075,7 +1085,6 @@ $( echo \"$2\" >> prueba.txt )
         		done
         	fi
         
-        
         	if [ $EXCLUDEDISK -eq 0  ]
         	then
         
@@ -1102,7 +1111,31 @@ $( echo \"$2\" >> prueba.txt )
                                 	if [ -e "$origin" ]
                                 	then
                                 		exec 5>&1	
-                                		VMKFSTOOLSOUT=$(vmkfstools -d thin -i "$origin" "$target" >&5 2>"$errfileb")
+                                		if [ "$4" = "rsync" ]
+                                		then
+                                			killRsync
+                                			RSYNCOUT=$("$PWD/xsibackup-rsync" -rlpDvzz  --progress --partial "$origin" "$target" >&5 2>"$errfileb")	
+                                			# And now the flat file
+                                			flatfile=$(grep -ri "\-flat.vmdk" "$origin" | awk '{ print $4 }')
+                                			flatfile=${flatfile//\"/}
+                                			vmdkfile=$( basename "$origin" )
+                                			vmdkdire=${origin//"$vmdkfile"/}
+                                			flatorigin="$vmdkdire/$flatfile"
+                                			flattarget="$2/$flatfile"
+                                			if [ -e "$flatorigin" ]
+                                			then
+                                				if [ -e "$flattarget" ]
+                                				then
+                                					RSYNCOUT=$("$PWD/xsibackup-rsync" -rlpDv --progress --omit-dir-times "$flatorigin" "$flattarget" >&5 2>"$errfileb")
+                                				else
+                                					RSYNCOUT=$("$PWD/xsibackup-rsync" -rlpDv --progress --whole-file --sparse "$flatorigin" "$flattarget" >&5 2>"$errfileb")
+                                				fi
+                                			else
+                                				$( ERR 33 "Missing file, cannot copy: $flatorigin" )
+                                			fi
+                                		else
+                                			VMKFSTOOLSOUT=$(vmkfstools -d thin -i "$origin" "$target" >&5 2>"$errfileb")
+                                		fi
                                 		exec 5>&-
                                 	else
                                 		$( ERR 33 "No disk found at: $origin" )
@@ -1520,8 +1553,6 @@ STARTVM=$(date +%s)
                 	echo "Excluding disks matching pattern: $EXCLUDEVMDK"
 		fi
 
-
-	
 	emailHTMLStr=$emailHTMLStr"<td><b>"$EXITCODE"</b></td>\n"
 
 	if [[ "$testmode" != "true" ]]
@@ -1545,14 +1576,13 @@ STARTVM=$(date +%s)
 				fi
 			fi
 		
-			# WRONG BLOCK
-			#if [ "$baksrvaddr" != "" ]
-			#then
-			#	KILLRS=$(killRsync "$baksrvaddr" "$baksrvport")
-			#	echo $KILLRS
-			#fi
+			if [ "$backupprog" = "rsync" ]
+			then
+				cloneVM $VMIDNU "$backuppoint/$VMDIRN" "$EXCLUDEVMDK" "$backupprog"
+			else
+				cloneVM $VMIDNU "$backuppoint/$newdirmask/$VMDIRN" "$EXCLUDEVMDK"
+			fi
 			
-			cloneVM $VMIDNU "$backuppoint/$newdirmask/$VMDIRN" "$EXCLUDEVMDK"
 			#CLONERETURN=$(cloneVM $VMIDNU "$backuppoint/$newdirmask/$VMDIRN")
 		
 		elif [ "$SERVERTYPE" = "NET" ]
@@ -1574,10 +1604,18 @@ STARTVM=$(date +%s)
 	fi
 
 	sleep 10
-	
-	if [[ $? != 0 ]]
+
+	ERR_FILE_SIZE=$( ls -la "$errfileb" | awk '{print $5}' )
+	if [ "$ERR_FILE_SIZE" != "0" ]
 	then
-		EXITCODE="KO"
+		VMCONTEXTERR=1
+	else
+		VMCONTEXTERR=0
+	fi                        
+	
+	if [[ $? != 0 -o $VMCONTEXTERR != 0 ]]
+	then
+		EXITCODE="KO!"
 	else
 		EXITCODE="OK"
 	fi
@@ -1710,14 +1748,17 @@ then
 		echo -ne "\r\n"
   		echo -ne $emailHTMLStr"\r\n"
   		echo -ne ".\r\n"
-  		echo -ne "quit"
+  		echo -ne "quit\r\n"
 		}
 
-		# TLS Session, for future versions, in the to do list
-		# openssl s_client -starttls smtp -connect smtp.server.com:25 -crlf -ign_eof
+		if [[ $smtpsec == "TLS" ]]
+		then		
+			# TLS Session, for future versions, in the to do list
+			mail_input | openssl s_client -starttls smtp -connect ${smtpsrv}:${smtpport} -ign_eof
+		else
+			mail_input | nc $smtpsrv $smtpport || err_exit
+		fi
 		
-		mail_input | nc $smtpsrv $smtpport || err_exit
-
 		# We close the SMTP port
 		esxcli network firewall ruleset set --ruleset-id=SMTPout --enabled=false
 		echo "Firewall rule SMTPout closed."	
